### ISSUE TITLE
インストール後に、初回起動時だけ「設定」のオンラインアカウント、共有でフリーズする

### ISSUE THREAD

**Issue by unknown-neko** [openyellowos/open-Yellow-os#2]
* 「設定」⇒「オンラインアカウント」
* 「設定」⇒「共有」

初回インストール直後だけ、フリーズする。

----------

一度ログアウト、再起動すれば再現しなくなる。(pacup無しで)
Debian12、Ubuntuの23.04でも再現する。

----------

ログアウト、再起動だけで対処できるため、致命的とは考えずサポートで案内

**Comment by toshio1822** [comment]
インストール後の初回起動時に「gnome-keyring-daemon」を再起動することで、
フリーズしなくなった。
https://github.com/openyellowos/open-Yellow-os/commit/85018c7785b716b9dbe3f727c3a1d8bf4834bb12
